### ISSUE TITLE
VoIP2Day link refers to inappropriate content.

### ISSUE THREAD

**Issue by braams** [miconda/sip-resources#10]
Hello!
It looks like VoIP2Day event's url is incorrect or the site was defaced. It has inappropriate content.

**Comment by miconda** [comment]
Thanks for spotting it, probably the domain was not prolonged and got in dirty hands, or maybe the server got compromised.

I checked the emails I had with the event organizers and the domain was the voip2day.com, the last emails received are pre-pandemic, during 2019. I will try to see if I can contact some of their people via other channels.

Meanwhile the reference was removed.
