### ISSUE TITLE
Add voip-patrol

### ISSUE THREAD

**Issue by supapo** [miconda/sip-resources#6]
Dear @miconda , thank you for the great awesome list.
Can you please add the [voip-patrol](https://github.com/igorolhovskiy/voip_patrol) to this list? it's a fork of [this ](https://github.com/jchavanton/voip_patrol)repo
Also, there is the [volts](https://github.com/igorolhovskiy/volts) project
You also can see the talk about it in the Kamailio con video (talking with you 😉) [here ](https://youtu.be/9NGu5LpGSMc?t=7645)

**Comment by miconda** [comment]
This was forgotten and aged -- volts was added a while ago, the fork of voip_patrol should be renamed if it diverged and it is no plan to merge back to original project, otherwise is confusing.
